apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h6vduykk7-java-springboot
  janus-idp.io/tekton: h6vduykk7-java-springboot
  backstage.io/kubernetes-id: h6vduykk7-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h6vduykk7-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
